version: '3.9'

services:
 web:
  image: tutum/apache-php
  hostname: web-user-php
  volumes:
   - ./app-php/db-data:/var/www/html
  ports: 
   - 8000:80
  networks:
   - frontend
   - backend

 db: 
   image: mariadb
   hostname: db
   volumes: 
    - ./db-data:/var/lib/mysql
   environment:
    - MARIADB_ROOT_PASSWORD=root
   networks:
    - backend
networks:
 frontend: 
 backend:
