version: '2.4'

services:
 web:
  image: tutum/apache-php
  hostname: web-user-php
  volumes:
   - ./php:/var/www/html
  ports: 
   - 8000:80
  networks:
   - frontend
   - backend
  db: 
   image: mariadb
   hostname: db
   volumes: 
    - ./my-db:/var/lib/mysql
   environment:
    - MARIADB_ROOT_PASSWORD=root
   networks:
    - backend
networks:
 frontend: 
 backend:
